export enum OrderStatus {

    ORDER_CONFIRMED = 'ORDER_CONFIRMED',
    ORDER_CANCELLED = 'ORDER_CANCELLED',
    ORDER_DELIVERED = 'ORDER_DELIVERED',
    PROCESSING = 'PROCESSING',
    AWAITING_PAYMENT = 'AWAITING_PAYMENT',

}